"""
Local dev pipeline — mirrors n8n Layer 2 for testing without n8n.cloud.

Not part of submission flow; use n8n webhook in production.
Run: uvicorn pipeline:app --host 127.0.0.1 --port 8090
"""

from __future__ import annotations

import os
import re
from typing import Any

import httpx
from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI(title="Local Listing Pipeline (Dev)", version="1.0.0")

GUARDRAILS_URL = os.getenv("GUARDRAILS_URL", "http://127.0.0.1:8001")
RAG_URL = os.getenv("RAG_URL", "http://127.0.0.1:8002")
IMAGE_URL = os.getenv("IMAGE_URL", "http://127.0.0.1:8003")
LANGGRAPH_URL = os.getenv("LANGGRAPH_URL", "http://127.0.0.1:8004")

RESIDENTIAL = {"apartment", "house", "villa"}
COMMERCIAL = {"office", "retail", "industrial"}


class ListingPayload(BaseModel):
    description: str
    image_urls: list[str] = Field(default_factory=list)
    agent_name: str = ""


def _post(client: httpx.Client, url: str, body: dict) -> dict:
    r = client.post(url, json=body, timeout=60.0)
    r.raise_for_status()
    return r.json()


def extract_fields(description: str) -> dict[str, Any]:
    text = description
    lower = text.lower()
    ptype = "other"
    if any(w in lower for w in ("apartment", "flat", "דירה")):
        ptype = "apartment"
    elif "house" in lower or "villa" in lower:
        ptype = "house" if "house" in lower else "villa"
    elif "office" in lower:
        ptype = "office"
    elif "retail" in lower or "shop" in lower:
        ptype = "retail"
    elif "industrial" in lower or "warehouse" in lower:
        ptype = "industrial"

    rooms = None
    m = re.search(r"(\d+)\s*[- ]?\s*(bed|br|bedroom|room)", lower)
    if m:
        rooms = int(m.group(1))

    price = None
    pm = re.search(r"([\d,]+)\s*(ils|nis|₪|usd|\$|eur|€)", lower)
    if pm:
        price = pm.group(0)

    features = []
    for kw in ("parking", "balcony", "renovated", "elevator", "sea view", "garden"):
        if kw in lower:
            features.append(kw)

    location = None
    loc = re.search(r"(?:in|at)\s+([A-Za-z\u0590-\u05FF\s'-]{3,40})", text)
    if loc:
        location = loc.group(1).strip()

    return {
        "property_type": ptype,
        "location": location,
        "price": price,
        "rooms": rooms,
        "key_features": features,
        "certifications": [],
    }


def build_brief(
    extracted: dict,
    rag: dict,
    images: list[dict],
    agent_name: str,
    description: str = "",
) -> str:
    lines = [
        f"# Listing brief — {extracted.get('property_type', 'property').title()}",
        "",
        f"**Agent:** {agent_name or 'N/A'}",
        f"**Location:** {extracted.get('location') or 'Not provided'}",
        f"**Price:** {extracted.get('price') or 'Not provided'}",
        f"**Rooms:** {extracted.get('rooms') or 'Not provided'}",
        "",
        "## Key features",
    ]
    feats = extracted.get("key_features") or []
    lines.append(", ".join(feats) if feats else "Not provided")
    lines.extend(["", "## Image condition"])
    if images:
        for img in images:
            lines.append(
                f"- {img.get('room_type')}: score {img.get('condition_score')}/5 "
                f"(confidence {img.get('confidence')})"
            )
    else:
        lines.append("No images supplied.")
    lines.extend(["", "## Market insight (RAG)", rag.get("insight", ""), "", "## Similar listings"])
    for item in rag.get("similar_listings", [])[:3]:
        lines.append(f"- {item.get('title')} ({item.get('id')})")
    lines.append("")
    lines.append("*Generated by local dev pipeline.*")
    brief = "\n".join(lines)
    if "FAIL_OUTPUT" in description:
        brief += "\n\nFAIL_OUTPUT legal guarantee (demo trigger for output guardrail)."
    return brief


def route_team(property_type: str) -> str:
    if property_type in RESIDENTIAL:
        return "residential"
    if property_type in COMMERCIAL:
        return "commercial"
    return "residential"


@app.get("/health")
def health():
    return {"status": "ok", "layer": "dev-local-pipeline"}


@app.post("/run")
def run_pipeline(payload: ListingPayload):
    with httpx.Client() as client:
        guard_in = _post(
            client,
            f"{GUARDRAILS_URL}/check/input",
            {"text": payload.description},
        )
        if not guard_in.get("pass"):
            return {
                "status": "rejected",
                "reason": guard_in.get("reason", "Input guardrail failed."),
            }

        extracted = extract_fields(payload.description)
        rag = _post(client, f"{RAG_URL}/query", {"description": payload.description})

        images: list[dict] = []
        for url in payload.image_urls:
            try:
                images.append(_post(client, f"{IMAGE_URL}/analyse", {"image_url": url}))
            except httpx.HTTPError:
                images.append(
                    {"room_type": "other", "condition_score": 0, "confidence": 0, "error": url}
                )

        if "renovation" in payload.description.lower() or "condition" in payload.description.lower():
            _post(
                client,
                f"{LANGGRAPH_URL}/agent/run",
                {"query": f"Renovation analysis: {payload.description[:500]}"},
            )

        brief = build_brief(
            extracted, rag, images, payload.agent_name, payload.description
        )
        guard_out = _post(client, f"{GUARDRAILS_URL}/check/output", {"text": brief})

        if not guard_out.get("pass"):
            return {
                "status": "review",
                "message": guard_out.get("reason", "Output requires human review."),
                "extracted_fields": extracted,
                "listing_brief": brief,
                "image_analysis": images,
                "similar_listings": rag.get("similar_listings"),
            }

        return {
            "status": "ok",
            "listing_brief": brief,
            "extracted_fields": extracted,
            "image_analysis": images,
            "similar_listings": rag.get("similar_listings"),
            "rag_insight": rag.get("insight"),
            "routing": route_team(extracted.get("property_type", "other")),
        }
